"""1 - Name: Homeward xctestrun routing validator tests.
2 - Description: Verifies exact target, UI application, runner, and test-bundle routing before Release E2E execution.
3 - Assumptions: Synthetic dictionaries use the stable xctestrun path tokens generated by Xcode.
4 - Expectations: Only one canonical Homeward Release E2E target is accepted.
"""

import copy
import unittest

from scripts.validate_xctestrun import (
    XCTestRunValidationError,
    validate_document,
)


class XCTestRunRoutingValidationTests(unittest.TestCase):
    """1 - Name: XCTest run routing validation suite.
    2 - Description: Mutates a canonical Release E2E target to exercise host, app, bundle, and cardinality checks.
    3 - Assumptions: Metadata is not an executable test target and path tokens resolve under one build-products root.
    4 - Expectations: Any target ambiguity or path substitution fails before application launch.
    """

    def setUp(self) -> None:
        self.document = {
            "__xctestrun_metadata__": {"FormatVersion": 2},
            "HomewardReleaseE2ETests": {
                "BlueprintName": "HomewardReleaseE2ETests",
                "UITargetAppPath": "__TESTROOT__/Release/Homeward.app",
                "TestHostPath":
                    "__TESTROOT__/Release/HomewardReleaseE2ETests-Runner.app",
                "TestBundlePath":
                    "__TESTHOST__/Contents/PlugIns/"
                    "HomewardReleaseE2ETests.xctest",
            },
        }

    def test_canonical_routing_succeeds(self):
        """1 - Name: Canonical routing acceptance.
        2 - Description: Validates the exact Release app and UI runner paths.
        3 - Assumptions: One test target follows the metadata record.
        4 - Expectations: Validation completes without an exception.
        """
        validate_document(self.document)

    def test_wrong_ui_target_fails_closed(self):
        """1 - Name: Wrong UI target rejection.
        2 - Description: Redirects the UI test from Homeward to another app path.
        3 - Assumptions: UITargetAppPath controls which application XCTest launches.
        4 - Expectations: Validation rejects the substituted application.
        """
        document = copy.deepcopy(self.document)
        document["HomewardReleaseE2ETests"]["UITargetAppPath"] = (
            "__TESTROOT__/Release/Other.app"
        )
        with self.assertRaisesRegex(
            XCTestRunValidationError,
            "Unexpected UITargetAppPath",
        ):
            validate_document(document)

    def test_additional_target_fails_closed(self):
        """1 - Name: Additional target rejection.
        2 - Description: Adds another executable test target to the run file.
        3 - Assumptions: Release evidence is authorized only by the dedicated lifecycle target.
        4 - Expectations: Validation rejects ambiguous multi-target execution.
        """
        document = copy.deepcopy(self.document)
        document["UnexpectedTests"] = {
            "BlueprintName": "UnexpectedTests"
        }
        with self.assertRaisesRegex(
            XCTestRunValidationError,
            "Expected one xctestrun target",
        ):
            validate_document(document)

    def test_wrong_test_bundle_fails_closed(self):
        """1 - Name: Wrong test bundle rejection.
        2 - Description: Redirects the runner to an unrelated plug-in.
        3 - Assumptions: The runner path alone cannot establish which test code executes.
        4 - Expectations: Validation rejects the substituted test bundle.
        """
        document = copy.deepcopy(self.document)
        document["HomewardReleaseE2ETests"]["TestBundlePath"] = (
            "__TESTHOST__/Contents/PlugIns/OtherTests.xctest"
        )
        with self.assertRaisesRegex(
            XCTestRunValidationError,
            "Unexpected TestBundlePath",
        ):
            validate_document(document)


if __name__ == "__main__":
    unittest.main()
